# Generated by Django 5.2.6 on 2025-09-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('text', models.TextField(verbose_name='Опис')),
                ('date', models.DateField(verbose_name='Дата створення відгуку')),
                ('typeplace', models.CharField(verbose_name='Тип місця')),
                ('location', models.CharField(blank=True, verbose_name='Локація')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
            ],
        ),
    ]
